### ISSUE TITLE
Estilo dos botões e direcionamento de páginas

### ISSUE THREAD

**Issue by ivynasantino** [OpenDevUFCG/andromedev#25]
O que acham de trocar as cores dos botões da tela inicial e deixar com a cor roxa e laranja assim como no guia e no sobre? E também ao invés de um texto com link para o cronograma deixar um botão?

Mais ou menos assim as mudanças:
1. 
![image](https://user-images.githubusercontent.com/18709508/88438709-b8cc0180-cddf-11ea-91ae-7170e506f82f.png)

2. 
![image](https://user-images.githubusercontent.com/18709508/88438738-c97c7780-cddf-11ea-922c-93341abb260d.png)

**Comment by thayannevls** [comment]
Achei muito boa a ideia! Ficou mais uniforme o estilo do site
