### ISSUE TITLE
Títulos de seções são escondidas pela header quando acessando pelo anchor link

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/andromedev#29]
**Descreva o bug**

A nossa header está com `position: fixed`, e ao clicar num link de um título de uma seção do markdown, o título da seção é escondida pela header.

**Reprodução do bug**

1. Vá para uma página no markdown
2. Clique em alguma header
3. Veja o erro, também teste dando reload.

**Comportamento desejado**
Que mostre o conteúdo todo da seção.

**Capturas de tela**
![Guia de Bordo _ Andromedev](https://user-images.githubusercontent.com/6867958/88489310-f9f01d00-cf69-11ea-9597-ada3de6f8688.gif)

**Desktop:**

- SO: Linux Ubuntu
- Navegador: Chrome

**Contexto adicional**
Utilizamos [este plugin](https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/) para criar os links para header automaticamente, segue algumas coisas que tentei:

- Adicionar a prop `offsetY` no plugin, não deu certo.
- Adicionar uma margin-top no className do anchor no plugin, também não deu certo.

**Comment by thayannevls** [comment]
Algumas soluções que tentei adaptar sem sucesso:
- https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header
- https://stackoverflow.com/questions/4086107/fixed-page-header-overlaps-in-page-anchors

Se alguém conseguir seria ótimo :smile:

**Comment by JGuilhermeCoelho** [comment]
Tentei aqui e não consegui também, fiz uma solução alternativa
![Screen Capture_google-chrome_20200825180041](https://user-images.githubusercontent.com/32929623/91227692-54150700-e6fd-11ea-8ea0-f1cf8c39a6a9.gif)

O header se "esconde" ao rolar a página pra baixo e reaparece ao rolar pra cima. Ao clicar no link do markdown ele se esonde novamente e dessa forma o título fica visível
