### ISSUE TITLE
Criação do componente de toolbar

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/andromedev#43]
**Descrição da melhoria:**
Descreva a melhoria e suas caracteristicas mais importantes

**Necessidade da melhoria:**
Descreva o porquê da melhoria ser necessaria

**Como ela pode ser implementada:**
Dê ideias de como a melhoria pode ser implementada no projeto

**Imagens:**
![image](https://user-images.githubusercontent.com/11728746/131589125-d3a59e2e-6007-449f-b736-c0d14e8f3741.png)

**Contexto adicional:**
Adicione qualquer informação adicional que achar necessaria

**Comment by RodrigoEC** [comment]
Posso ficar com essa issue? :eyes:

**Comment by JoseRenan** [comment]
> Posso ficar com essa issue? 👀

Eita @RodrigoEC,ainda nn tá mto bem descrita, mas pode sim kkkkkkkk basicamente é a toolbar como tá no print mesmo.

Ah, lembra que a branch que tamo fazendo o site de 2022 é a `main` e não a `master` ok?

**Comment by JoseRenan** [comment]
> Boa noite, eu poderia pegar esse?

Boaa, pode pegar!

**Comment by JoseRenan** [comment]
Done em #61
