### ISSUE TITLE
Criação do Card de cronograma

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/andromedev#47]
**Descrição da issue:**

Cada Card de cronograma terá datas importantes definidas no cronograma do evento, com uma breve descrição do que ocorrerá naquele dia, em que horário e em que lugar (discord, youtube e etc).  O Card ficará laranja quando o dia do evento/inscrição chegar.

**Como ela pode ser implementada:**

A ideia é que ao implementar essa issue, tenhamos um componente com essa estrutura:

```tsx
<ScheduleCard 
  title="Abertura de inscrição de organizações"
  startTime={date}
  endTime={date}
  place="Discord"
  placeLink="discord.gg" />
```

**Imagens:**
![image](https://user-images.githubusercontent.com/11728746/131589543-4101907c-5045-48d7-bf6b-535c773ea6f1.png)

**Comment by jonathasbsouza** [comment]
Oi, vou pegar essa!

**Comment by JoseRenan** [comment]
> Oi, vou pegar essa!

Vai que é tua 🚀
