### ISSUE TITLE
Criação do Card de projeto e avatar de organização

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/andromedev#48]
**Descrição da issue:**
Criação do Card do projeto e avatar de organização. O Card irá conter informações sobre o projeto. O avatar será um componente que vai ser reutilizado em outras partes do site, por isso é bom criá-lo separadamente para utilizar no card.

**Como ela pode ser implementada:**

A ideia é que ao implementar essa issue, tenhamos um componente com essa estrutura:

```tsx
 <ProjectCard
    name="ERP Acadêmico"
    description="pipipipopopo"
    category="Implementação de features" />
```

O avatar terá uma estrutura parecida com esta:

```tsx
<Avatar src="link da imagem" />
```

**Imagens:**
![image](https://user-images.githubusercontent.com/11728746/131589679-56772bff-e60a-459c-9c20-1f591761f65b.png)

![image](https://user-images.githubusercontent.com/11728746/131589739-cb1c29b2-2361-4bdf-a566-f3cda4ec7bc8.png)

**Contexto adicional:**
O avatar será ajustado no css, da forma que você achar mais coerente :D

**Comment by JoseRenan** [comment]
Acabo de ver que o componente de avatar já existe no chakra-ui ([aqui](https://chakra-ui.com/docs/media-and-icons/avatar)) só reusar msm

**Comment by emannuellymelo** [comment]
quero começar por essa

**Comment by JoseRenan** [comment]
> quero começar por essa

Vai que é tua!!
