### ISSUE TITLE
Criação do componente HomeSection

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/andromedev#49]
**Descrição da issue:**
Criação do componente HomeSection que representa uma seção da página inicial do site com um titulo, alguma informação e um link.

Ela pode funcionar em 3 variações, como é visto nos exemplos abaixo, porém, sempre contendo as mesmas informações (titulo, alguma informação e um link).

**Como ela pode ser implementada:**

A ideia é que ao implementar essa issue, tenhamos um componente com essa estrutura:

```tsx
<HomeSection 
    variant="primary" 
    title="Sua jornada começa aqui"
    buttonLabel="Inscreva-se"
    paragraph={<p>O Andromedev é um evento realizado pela organização estudantil OpenDevUFCG com o intuito de incentivar a participação de estudantes da UFCG em projetos open source.</p>} />
```

> A `variant` poderá ser do tipo primary, secondary ou centered, cada uma delas tá sendo representada nas imagens abaixo.

> O `paragraph` pode ser qualquer elemento JSX, a ideia é que isso fique mais customizável, pra permitir links, negritos e etc, por isso seria melhor do que um tipo texto.

> Você verá que o componente já existe em `src/components/home/HomeSection.tsx`, mas é apenas um esboço e sem nenhuma estilização e nenhuma diferença entre as variantes.

**Imagens:**

Variant primary
![image](https://user-images.githubusercontent.com/11728746/131590016-f882ec86-d8e9-431c-be59-7347f3e5d52b.png)

Variant secondary
![image](https://user-images.githubusercontent.com/11728746/131590134-9a60227a-8d57-4731-81e6-f6ccf1a0d955.png)

Variant centered
![image](https://user-images.githubusercontent.com/11728746/131590196-7921457d-2f22-4178-87fe-0a76585eccf6.png)

**Contexto adicional:**
 Os botões estão sendo implementados na issue #50, caso ela ainda não esteja pronta, seria uma boa pegar ela antes e em seguida pegar essa.

**Comment by Klaywert** [comment]
Posso começar com essa?

**Comment by JoseRenan** [comment]
> Posso começar com essa?

Vai que é tua
