### ISSUE TITLE
Implementação do Carousel de depoimentos

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/andromedev#59]
**Descrição da melhoria:**
Atualmente temos o componente `TestimonialCard` que representa o depoimento de alguém de algum andromedev anterior. Agora precisamos que seja feito um componente que liste vários `TestimonialCards` e tenha setinhas pra o usuário conseguir iterar nesses depoimentos. (Vide print abaixo)

**Como ela pode ser implementada:**

O conteúdo das páginas está sendo gerado através de um CMS (que pra nós serve como uma API que vai nos fornecer os dados pra construir as páginas). É de lá que estão vindo os dados do que deve aparecer na tela.

O nosso `SliceZone` é o componente que recebe os dados do CMS, e verifica qual tipo de dado é e qual componente deve ser usado pra exibir aquele tipo de dado. Por exemplo, pra exibir o conteúdo das seções da tela principal, é feito um `switch case`, caso o tipo de dado seja `homesection`, mostre o componente `HomeSection`...

Para exibir o carousel de depoimentos na tela principal, você só precisa adicionar mais uma condição nesse `switch case`,
Algo como:

```tsx
case 'testimonials':
      return <TestimonialCarousel {/* passe aqui as props */} />
```

> 💡  Você pode dar uma olhada nos dados que o CMS lhe dá pra passar pro TestimonialCarousel dando um `console.log(slice)` dentro desse case, e aí vai ser printado exatamente os dados de depoimentos que o CMS dá

**Imagens:**
<img width="957" alt="image" src="https://user-images.githubusercontent.com/11728746/136868564-af3d66c1-afc0-4692-951f-4d6ff4313000.png">

**Contexto adicional:**

Parece meio complicado? kkkkkkk pode perguntar aqui qualquer coisa, e se precisar chama no [discord](https://chat.opendevufcg.org) que a gente faz uma call e eu explico tudo certim

**Comment by Klaywert** [comment]
opa, boa noite.
posso trabalhar nessa issue.
oq achas?
